export const labels = {
  page_header_headline: 'Movie Search',
  page_header_description:
    'Search for movies, view details, and explore your favorite films. Start your cinematic journey now!',
  movie_user_rating: 'User Rating',
  movie_search_placeholder: 'Type two leter to search for movies...',
  movie_search_button: 'Search',
  movie_search_no_results: 'No Results',
  movie_search_no_results_description: 'No results found. Please try a different search term.',
  movie_search_error_headline: 'Error Occurred',
  movie_search_error_description: 'An error occurred while fetching movie data. Please try again later.',
  no_similar_movies: 'No similar movies found.',
  no_similar_movies_description: "We couldn't find any similar movies for this title.",
  movie_no_media: 'No Media',
  movie_no_media_description: 'No media available for this movie.',
  movie_favorites_headline: 'Your Favorite Movies',
  movie_favorites_description: 'Here are the movies you have added to your favorites.',
  movies_appares_in: 'Movies Appearing In',
  movie_actor_headline: 'Movies Featuring',
  movie_no_favorites: 'No Favorites',
  no_cast: 'Sounds weird but there is no cast information available for this movie.',
  movie_no_favorites_description: 'You have not added any movies to your favorites yet.',
  movie_no_premiere_date: 'No premiere date available.',
  movie_trending_headline: 'Trending Movies This Week',
  common: {
    loading: 'Loading...',
    error: 'An error occurred. Please try again later.',
    back_to_home: 'Back to Home',
    back_to_search: 'Back to Search',
    view_details: 'View Details',
    add_to_favorites: 'Add to Favorites',
    cast: 'Cast',
    similar_movies: 'Similar Movies',
    movie_details: 'Movie Details',
    movie_gallery: 'Movie Gallery',
    movie_trailer: 'Movie Trailer',
    minutes: 'minutes',
  },
}
