export const genres = [
  {
    id: 28,
    name: 'Action',
  },
  {
    id: 12,
    name: 'Adventure',
  },
  {
    id: 16,
    name: 'Animation',
  },
  {
    id: 35,
    name: 'Comedy',
  },
  {
    id: 80,
    name: 'Crime',
  },
  {
    id: 99,
    name: 'Documentary',
  },
  {
    id: 18,
    name: 'Drama',
  },
  {
    id: 10751,
    name: 'Family',
  },
  {
    id: 14,
    name: 'Fantasy',
  },
  {
    id: 36,
    name: 'History',
  },
  {
    id: 27,
    name: 'Horror',
  },
  {
    id: 10402,
    name: 'Music',
  },
  {
    id: 9648,
    name: 'Mystery',
  },
  {
    id: 10749,
    name: 'Romance',
  },
  {
    id: 878,
    name: 'Science Fiction',
  },
  {
    id: 10770,
    name: 'TV Movie',
  },
  {
    id: 53,
    name: 'Thriller',
  },
  {
    id: 10752,
    name: 'War',
  },
  {
    id: 37,
    name: 'Western',
  },
]

export const countries = [
  {
    iso_3166_1: 'AD',
    english_name: 'Andorra',
    native_name: 'Andorra',
  },
  {
    iso_3166_1: 'AE',
    english_name: 'United Arab Emirates',
    native_name: 'United Arab Emirates',
  },
  {
    iso_3166_1: 'AF',
    english_name: 'Afghanistan',
    native_name: 'Afghanistan',
  },
  {
    iso_3166_1: 'AG',
    english_name: 'Antigua and Barbuda',
    native_name: 'Antigua & Barbuda',
  },
  {
    iso_3166_1: 'AI',
    english_name: 'Anguilla',
    native_name: 'Anguilla',
  },
  {
    iso_3166_1: 'AL',
    english_name: 'Albania',
    native_name: 'Albania',
  },
  {
    iso_3166_1: 'AM',
    english_name: 'Armenia',
    native_name: 'Armenia',
  },
  {
    iso_3166_1: 'AN',
    english_name: 'Netherlands Antilles',
    native_name: 'Netherlands Antilles',
  },
  {
    iso_3166_1: 'AO',
    english_name: 'Angola',
    native_name: 'Angola',
  },
  {
    iso_3166_1: 'AQ',
    english_name: 'Antarctica',
    native_name: 'Antarctica',
  },
  {
    iso_3166_1: 'AR',
    english_name: 'Argentina',
    native_name: 'Argentina',
  },
  {
    iso_3166_1: 'AS',
    english_name: 'American Samoa',
    native_name: 'American Samoa',
  },
  {
    iso_3166_1: 'AT',
    english_name: 'Austria',
    native_name: 'Austria',
  },
  {
    iso_3166_1: 'AU',
    english_name: 'Australia',
    native_name: 'Australia',
  },
  {
    iso_3166_1: 'AW',
    english_name: 'Aruba',
    native_name: 'Aruba',
  },
  {
    iso_3166_1: 'AZ',
    english_name: 'Azerbaijan',
    native_name: 'Azerbaijan',
  },
  {
    iso_3166_1: 'BA',
    english_name: 'Bosnia and Herzegovina',
    native_name: 'Bosnia & Herzegovina',
  },
  {
    iso_3166_1: 'BB',
    english_name: 'Barbados',
    native_name: 'Barbados',
  },
  {
    iso_3166_1: 'BD',
    english_name: 'Bangladesh',
    native_name: 'Bangladesh',
  },
  {
    iso_3166_1: 'BE',
    english_name: 'Belgium',
    native_name: 'Belgium',
  },
  {
    iso_3166_1: 'BF',
    english_name: 'Burkina Faso',
    native_name: 'Burkina Faso',
  },
  {
    iso_3166_1: 'BG',
    english_name: 'Bulgaria',
    native_name: 'Bulgaria',
  },
  {
    iso_3166_1: 'BH',
    english_name: 'Bahrain',
    native_name: 'Bahrain',
  },
  {
    iso_3166_1: 'BI',
    english_name: 'Burundi',
    native_name: 'Burundi',
  },
  {
    iso_3166_1: 'BJ',
    english_name: 'Benin',
    native_name: 'Benin',
  },
  {
    iso_3166_1: 'BM',
    english_name: 'Bermuda',
    native_name: 'Bermuda',
  },
  {
    iso_3166_1: 'BN',
    english_name: 'Brunei Darussalam',
    native_name: 'Brunei',
  },
  {
    iso_3166_1: 'BO',
    english_name: 'Bolivia',
    native_name: 'Bolivia',
  },
  {
    iso_3166_1: 'BR',
    english_name: 'Brazil',
    native_name: 'Brazil',
  },
  {
    iso_3166_1: 'BS',
    english_name: 'Bahamas',
    native_name: 'Bahamas',
  },
  {
    iso_3166_1: 'BT',
    english_name: 'Bhutan',
    native_name: 'Bhutan',
  },
  {
    iso_3166_1: 'BU',
    english_name: 'Burma',
    native_name: 'Burma',
  },
  {
    iso_3166_1: 'BV',
    english_name: 'Bouvet Island',
    native_name: 'Bouvet Island',
  },
  {
    iso_3166_1: 'BW',
    english_name: 'Botswana',
    native_name: 'Botswana',
  },
  {
    iso_3166_1: 'BY',
    english_name: 'Belarus',
    native_name: 'Belarus',
  },
  {
    iso_3166_1: 'BZ',
    english_name: 'Belize',
    native_name: 'Belize',
  },
  {
    iso_3166_1: 'CA',
    english_name: 'Canada',
    native_name: 'Canada',
  },
  {
    iso_3166_1: 'CC',
    english_name: 'Cocos  Islands',
    native_name: 'Cocos (Keeling) Islands',
  },
  {
    iso_3166_1: 'CD',
    english_name: 'Congo',
    native_name: 'Democratic Republic of the Congo (Kinshasa)',
  },
  {
    iso_3166_1: 'CF',
    english_name: 'Central African Republic',
    native_name: 'Central African Republic',
  },
  {
    iso_3166_1: 'CG',
    english_name: 'Congo',
    native_name: 'Republic of the Congo (Brazzaville)',
  },
  {
    iso_3166_1: 'CH',
    english_name: 'Switzerland',
    native_name: 'Switzerland',
  },
  {
    iso_3166_1: 'CI',
    english_name: "Cote D'Ivoire",
    native_name: 'Côte d’Ivoire',
  },
  {
    iso_3166_1: 'CK',
    english_name: 'Cook Islands',
    native_name: 'Cook Islands',
  },
  {
    iso_3166_1: 'CL',
    english_name: 'Chile',
    native_name: 'Chile',
  },
  {
    iso_3166_1: 'CM',
    english_name: 'Cameroon',
    native_name: 'Cameroon',
  },
  {
    iso_3166_1: 'CN',
    english_name: 'China',
    native_name: 'China',
  },
  {
    iso_3166_1: 'CO',
    english_name: 'Colombia',
    native_name: 'Colombia',
  },
  {
    iso_3166_1: 'CR',
    english_name: 'Costa Rica',
    native_name: 'Costa Rica',
  },
  {
    iso_3166_1: 'CS',
    english_name: 'Serbia and Montenegro',
    native_name: 'Serbia and Montenegro',
  },
  {
    iso_3166_1: 'CU',
    english_name: 'Cuba',
    native_name: 'Cuba',
  },
  {
    iso_3166_1: 'CV',
    english_name: 'Cape Verde',
    native_name: 'Cape Verde',
  },
  {
    iso_3166_1: 'CX',
    english_name: 'Christmas Island',
    native_name: 'Christmas Island',
  },
  {
    iso_3166_1: 'CY',
    english_name: 'Cyprus',
    native_name: 'Cyprus',
  },
  {
    iso_3166_1: 'CZ',
    english_name: 'Czech Republic',
    native_name: 'Czech Republic',
  },
  {
    iso_3166_1: 'DE',
    english_name: 'Germany',
    native_name: 'Germany',
  },
  {
    iso_3166_1: 'DJ',
    english_name: 'Djibouti',
    native_name: 'Djibouti',
  },
  {
    iso_3166_1: 'DK',
    english_name: 'Denmark',
    native_name: 'Denmark',
  },
  {
    iso_3166_1: 'DM',
    english_name: 'Dominica',
    native_name: 'Dominica',
  },
  {
    iso_3166_1: 'DO',
    english_name: 'Dominican Republic',
    native_name: 'Dominican Republic',
  },
  {
    iso_3166_1: 'DZ',
    english_name: 'Algeria',
    native_name: 'Algeria',
  },
  {
    iso_3166_1: 'EC',
    english_name: 'Ecuador',
    native_name: 'Ecuador',
  },
  {
    iso_3166_1: 'EE',
    english_name: 'Estonia',
    native_name: 'Estonia',
  },
  {
    iso_3166_1: 'EG',
    english_name: 'Egypt',
    native_name: 'Egypt',
  },
  {
    iso_3166_1: 'EH',
    english_name: 'Western Sahara',
    native_name: 'Western Sahara',
  },
  {
    iso_3166_1: 'ER',
    english_name: 'Eritrea',
    native_name: 'Eritrea',
  },
  {
    iso_3166_1: 'ES',
    english_name: 'Spain',
    native_name: 'Spain',
  },
  {
    iso_3166_1: 'ET',
    english_name: 'Ethiopia',
    native_name: 'Ethiopia',
  },
  {
    iso_3166_1: 'FI',
    english_name: 'Finland',
    native_name: 'Finland',
  },
  {
    iso_3166_1: 'FJ',
    english_name: 'Fiji',
    native_name: 'Fiji',
  },
  {
    iso_3166_1: 'FK',
    english_name: 'Falkland Islands',
    native_name: 'Falkland Islands',
  },
  {
    iso_3166_1: 'FM',
    english_name: 'Micronesia',
    native_name: 'Micronesia',
  },
  {
    iso_3166_1: 'FO',
    english_name: 'Faeroe Islands',
    native_name: 'Faroe Islands',
  },
  {
    iso_3166_1: 'FR',
    english_name: 'France',
    native_name: 'France',
  },
  {
    iso_3166_1: 'GA',
    english_name: 'Gabon',
    native_name: 'Gabon',
  },
  {
    iso_3166_1: 'GB',
    english_name: 'United Kingdom',
    native_name: 'United Kingdom',
  },
  {
    iso_3166_1: 'GD',
    english_name: 'Grenada',
    native_name: 'Grenada',
  },
  {
    iso_3166_1: 'GE',
    english_name: 'Georgia',
    native_name: 'Georgia',
  },
  {
    iso_3166_1: 'GF',
    english_name: 'French Guiana',
    native_name: 'French Guiana',
  },
  {
    iso_3166_1: 'GH',
    english_name: 'Ghana',
    native_name: 'Ghana',
  },
  {
    iso_3166_1: 'GI',
    english_name: 'Gibraltar',
    native_name: 'Gibraltar',
  },
  {
    iso_3166_1: 'GL',
    english_name: 'Greenland',
    native_name: 'Greenland',
  },
  {
    iso_3166_1: 'GM',
    english_name: 'Gambia',
    native_name: 'Gambia',
  },
  {
    iso_3166_1: 'GN',
    english_name: 'Guinea',
    native_name: 'Guinea',
  },
  {
    iso_3166_1: 'GP',
    english_name: 'Guadaloupe',
    native_name: 'Guadeloupe',
  },
  {
    iso_3166_1: 'GQ',
    english_name: 'Equatorial Guinea',
    native_name: 'Equatorial Guinea',
  },
  {
    iso_3166_1: 'GR',
    english_name: 'Greece',
    native_name: 'Greece',
  },
  {
    iso_3166_1: 'GS',
    english_name: 'South Georgia and the South Sandwich Islands',
    native_name: 'South Georgia & South Sandwich Islands',
  },
  {
    iso_3166_1: 'GT',
    english_name: 'Guatemala',
    native_name: 'Guatemala',
  },
  {
    iso_3166_1: 'GU',
    english_name: 'Guam',
    native_name: 'Guam',
  },
  {
    iso_3166_1: 'GW',
    english_name: 'Guinea-Bissau',
    native_name: 'Guinea-Bissau',
  },
  {
    iso_3166_1: 'GY',
    english_name: 'Guyana',
    native_name: 'Guyana',
  },
  {
    iso_3166_1: 'HK',
    english_name: 'Hong Kong',
    native_name: 'Hong Kong SAR China',
  },
  {
    iso_3166_1: 'HM',
    english_name: 'Heard and McDonald Islands',
    native_name: 'Heard & McDonald Islands',
  },
  {
    iso_3166_1: 'HN',
    english_name: 'Honduras',
    native_name: 'Honduras',
  },
  {
    iso_3166_1: 'HR',
    english_name: 'Croatia',
    native_name: 'Croatia',
  },
  {
    iso_3166_1: 'HT',
    english_name: 'Haiti',
    native_name: 'Haiti',
  },
  {
    iso_3166_1: 'HU',
    english_name: 'Hungary',
    native_name: 'Hungary',
  },
  {
    iso_3166_1: 'ID',
    english_name: 'Indonesia',
    native_name: 'Indonesia',
  },
  {
    iso_3166_1: 'IE',
    english_name: 'Ireland',
    native_name: 'Ireland',
  },
  {
    iso_3166_1: 'IL',
    english_name: 'Israel',
    native_name: 'Israel',
  },
  {
    iso_3166_1: 'IN',
    english_name: 'India',
    native_name: 'India',
  },
  {
    iso_3166_1: 'IO',
    english_name: 'British Indian Ocean Territory',
    native_name: 'British Indian Ocean Territory',
  },
  {
    iso_3166_1: 'IQ',
    english_name: 'Iraq',
    native_name: 'Iraq',
  },
  {
    iso_3166_1: 'IR',
    english_name: 'Iran',
    native_name: 'Iran',
  },
  {
    iso_3166_1: 'IS',
    english_name: 'Iceland',
    native_name: 'Iceland',
  },
  {
    iso_3166_1: 'IT',
    english_name: 'Italy',
    native_name: 'Italy',
  },
  {
    iso_3166_1: 'JM',
    english_name: 'Jamaica',
    native_name: 'Jamaica',
  },
  {
    iso_3166_1: 'JO',
    english_name: 'Jordan',
    native_name: 'Jordan',
  },
  {
    iso_3166_1: 'JP',
    english_name: 'Japan',
    native_name: 'Japan',
  },
  {
    iso_3166_1: 'KE',
    english_name: 'Kenya',
    native_name: 'Kenya',
  },
  {
    iso_3166_1: 'KG',
    english_name: 'Kyrgyz Republic',
    native_name: 'Kyrgyzstan',
  },
  {
    iso_3166_1: 'KH',
    english_name: 'Cambodia',
    native_name: 'Cambodia',
  },
  {
    iso_3166_1: 'KI',
    english_name: 'Kiribati',
    native_name: 'Kiribati',
  },
  {
    iso_3166_1: 'KM',
    english_name: 'Comoros',
    native_name: 'Comoros',
  },
  {
    iso_3166_1: 'KN',
    english_name: 'St. Kitts and Nevis',
    native_name: 'St. Kitts & Nevis',
  },
  {
    iso_3166_1: 'KP',
    english_name: 'North Korea',
    native_name: 'North Korea',
  },
  {
    iso_3166_1: 'KR',
    english_name: 'South Korea',
    native_name: 'South Korea',
  },
  {
    iso_3166_1: 'KW',
    english_name: 'Kuwait',
    native_name: 'Kuwait',
  },
  {
    iso_3166_1: 'KY',
    english_name: 'Cayman Islands',
    native_name: 'Cayman Islands',
  },
  {
    iso_3166_1: 'KZ',
    english_name: 'Kazakhstan',
    native_name: 'Kazakhstan',
  },
  {
    iso_3166_1: 'LA',
    english_name: "Lao People's Democratic Republic",
    native_name: 'Laos',
  },
  {
    iso_3166_1: 'LB',
    english_name: 'Lebanon',
    native_name: 'Lebanon',
  },
  {
    iso_3166_1: 'LC',
    english_name: 'St. Lucia',
    native_name: 'St. Lucia',
  },
  {
    iso_3166_1: 'LI',
    english_name: 'Liechtenstein',
    native_name: 'Liechtenstein',
  },
  {
    iso_3166_1: 'LK',
    english_name: 'Sri Lanka',
    native_name: 'Sri Lanka',
  },
  {
    iso_3166_1: 'LR',
    english_name: 'Liberia',
    native_name: 'Liberia',
  },
  {
    iso_3166_1: 'LS',
    english_name: 'Lesotho',
    native_name: 'Lesotho',
  },
  {
    iso_3166_1: 'LT',
    english_name: 'Lithuania',
    native_name: 'Lithuania',
  },
  {
    iso_3166_1: 'LU',
    english_name: 'Luxembourg',
    native_name: 'Luxembourg',
  },
  {
    iso_3166_1: 'LV',
    english_name: 'Latvia',
    native_name: 'Latvia',
  },
  {
    iso_3166_1: 'LY',
    english_name: 'Libyan Arab Jamahiriya',
    native_name: 'Libya',
  },
  {
    iso_3166_1: 'MA',
    english_name: 'Morocco',
    native_name: 'Morocco',
  },
  {
    iso_3166_1: 'MC',
    english_name: 'Monaco',
    native_name: 'Monaco',
  },
  {
    iso_3166_1: 'MD',
    english_name: 'Moldova',
    native_name: 'Moldova',
  },
  {
    iso_3166_1: 'ME',
    english_name: 'Montenegro',
    native_name: 'Montenegro',
  },
  {
    iso_3166_1: 'MG',
    english_name: 'Madagascar',
    native_name: 'Madagascar',
  },
  {
    iso_3166_1: 'MH',
    english_name: 'Marshall Islands',
    native_name: 'Marshall Islands',
  },
  {
    iso_3166_1: 'MK',
    english_name: 'Macedonia',
    native_name: 'Macedonia',
  },
  {
    iso_3166_1: 'ML',
    english_name: 'Mali',
    native_name: 'Mali',
  },
  {
    iso_3166_1: 'MM',
    english_name: 'Myanmar',
    native_name: 'Myanmar (Burma)',
  },
  {
    iso_3166_1: 'MN',
    english_name: 'Mongolia',
    native_name: 'Mongolia',
  },
  {
    iso_3166_1: 'MO',
    english_name: 'Macao',
    native_name: 'Macau SAR China',
  },
  {
    iso_3166_1: 'MP',
    english_name: 'Northern Mariana Islands',
    native_name: 'Northern Mariana Islands',
  },
  {
    iso_3166_1: 'MQ',
    english_name: 'Martinique',
    native_name: 'Martinique',
  },
  {
    iso_3166_1: 'MR',
    english_name: 'Mauritania',
    native_name: 'Mauritania',
  },
  {
    iso_3166_1: 'MS',
    english_name: 'Montserrat',
    native_name: 'Montserrat',
  },
  {
    iso_3166_1: 'MT',
    english_name: 'Malta',
    native_name: 'Malta',
  },
  {
    iso_3166_1: 'MU',
    english_name: 'Mauritius',
    native_name: 'Mauritius',
  },
  {
    iso_3166_1: 'MV',
    english_name: 'Maldives',
    native_name: 'Maldives',
  },
  {
    iso_3166_1: 'MW',
    english_name: 'Malawi',
    native_name: 'Malawi',
  },
  {
    iso_3166_1: 'MX',
    english_name: 'Mexico',
    native_name: 'Mexico',
  },
  {
    iso_3166_1: 'MY',
    english_name: 'Malaysia',
    native_name: 'Malaysia',
  },
  {
    iso_3166_1: 'MZ',
    english_name: 'Mozambique',
    native_name: 'Mozambique',
  },
  {
    iso_3166_1: 'NA',
    english_name: 'Namibia',
    native_name: 'Namibia',
  },
  {
    iso_3166_1: 'NC',
    english_name: 'New Caledonia',
    native_name: 'New Caledonia',
  },
  {
    iso_3166_1: 'NE',
    english_name: 'Niger',
    native_name: 'Niger',
  },
  {
    iso_3166_1: 'NF',
    english_name: 'Norfolk Island',
    native_name: 'Norfolk Island',
  },
  {
    iso_3166_1: 'NG',
    english_name: 'Nigeria',
    native_name: 'Nigeria',
  },
  {
    iso_3166_1: 'NI',
    english_name: 'Nicaragua',
    native_name: 'Nicaragua',
  },
  {
    iso_3166_1: 'NL',
    english_name: 'Netherlands',
    native_name: 'Netherlands',
  },
  {
    iso_3166_1: 'NO',
    english_name: 'Norway',
    native_name: 'Norway',
  },
  {
    iso_3166_1: 'NP',
    english_name: 'Nepal',
    native_name: 'Nepal',
  },
  {
    iso_3166_1: 'NR',
    english_name: 'Nauru',
    native_name: 'Nauru',
  },
  {
    iso_3166_1: 'NU',
    english_name: 'Niue',
    native_name: 'Niue',
  },
  {
    iso_3166_1: 'NZ',
    english_name: 'New Zealand',
    native_name: 'New Zealand',
  },
  {
    iso_3166_1: 'OM',
    english_name: 'Oman',
    native_name: 'Oman',
  },
  {
    iso_3166_1: 'PA',
    english_name: 'Panama',
    native_name: 'Panama',
  },
  {
    iso_3166_1: 'PE',
    english_name: 'Peru',
    native_name: 'Peru',
  },
  {
    iso_3166_1: 'PF',
    english_name: 'French Polynesia',
    native_name: 'French Polynesia',
  },
  {
    iso_3166_1: 'PG',
    english_name: 'Papua New Guinea',
    native_name: 'Papua New Guinea',
  },
  {
    iso_3166_1: 'PH',
    english_name: 'Philippines',
    native_name: 'Philippines',
  },
  {
    iso_3166_1: 'PK',
    english_name: 'Pakistan',
    native_name: 'Pakistan',
  },
  {
    iso_3166_1: 'PL',
    english_name: 'Poland',
    native_name: 'Poland',
  },
  {
    iso_3166_1: 'PM',
    english_name: 'St. Pierre and Miquelon',
    native_name: 'St. Pierre & Miquelon',
  },
  {
    iso_3166_1: 'PN',
    english_name: 'Pitcairn Island',
    native_name: 'Pitcairn Islands',
  },
  {
    iso_3166_1: 'PR',
    english_name: 'Puerto Rico',
    native_name: 'Puerto Rico',
  },
  {
    iso_3166_1: 'PS',
    english_name: 'Palestinian Territory',
    native_name: 'Palestinian Territories',
  },
  {
    iso_3166_1: 'PT',
    english_name: 'Portugal',
    native_name: 'Portugal',
  },
  {
    iso_3166_1: 'PW',
    english_name: 'Palau',
    native_name: 'Palau',
  },
  {
    iso_3166_1: 'PY',
    english_name: 'Paraguay',
    native_name: 'Paraguay',
  },
  {
    iso_3166_1: 'QA',
    english_name: 'Qatar',
    native_name: 'Qatar',
  },
  {
    iso_3166_1: 'RE',
    english_name: 'Reunion',
    native_name: 'Réunion',
  },
  {
    iso_3166_1: 'RO',
    english_name: 'Romania',
    native_name: 'Romania',
  },
  {
    iso_3166_1: 'RS',
    english_name: 'Serbia',
    native_name: 'Serbia',
  },
  {
    iso_3166_1: 'RU',
    english_name: 'Russia',
    native_name: 'Russia',
  },
  {
    iso_3166_1: 'RW',
    english_name: 'Rwanda',
    native_name: 'Rwanda',
  },
  {
    iso_3166_1: 'SA',
    english_name: 'Saudi Arabia',
    native_name: 'Saudi Arabia',
  },
  {
    iso_3166_1: 'SB',
    english_name: 'Solomon Islands',
    native_name: 'Solomon Islands',
  },
  {
    iso_3166_1: 'SC',
    english_name: 'Seychelles',
    native_name: 'Seychelles',
  },
  {
    iso_3166_1: 'SD',
    english_name: 'Sudan',
    native_name: 'Sudan',
  },
  {
    iso_3166_1: 'SE',
    english_name: 'Sweden',
    native_name: 'Sweden',
  },
  {
    iso_3166_1: 'SG',
    english_name: 'Singapore',
    native_name: 'Singapore',
  },
  {
    iso_3166_1: 'SH',
    english_name: 'St. Helena',
    native_name: 'St. Helena',
  },
  {
    iso_3166_1: 'SI',
    english_name: 'Slovenia',
    native_name: 'Slovenia',
  },
  {
    iso_3166_1: 'SJ',
    english_name: 'Svalbard & Jan Mayen Islands',
    native_name: 'Svalbard & Jan Mayen',
  },
  {
    iso_3166_1: 'SK',
    english_name: 'Slovakia',
    native_name: 'Slovakia',
  },
  {
    iso_3166_1: 'SL',
    english_name: 'Sierra Leone',
    native_name: 'Sierra Leone',
  },
  {
    iso_3166_1: 'SM',
    english_name: 'San Marino',
    native_name: 'San Marino',
  },
  {
    iso_3166_1: 'SN',
    english_name: 'Senegal',
    native_name: 'Senegal',
  },
  {
    iso_3166_1: 'SO',
    english_name: 'Somalia',
    native_name: 'Somalia',
  },
  {
    iso_3166_1: 'SR',
    english_name: 'Suriname',
    native_name: 'Suriname',
  },
  {
    iso_3166_1: 'SS',
    english_name: 'South Sudan',
    native_name: 'South Sudan',
  },
  {
    iso_3166_1: 'ST',
    english_name: 'Sao Tome and Principe',
    native_name: 'São Tomé & Príncipe',
  },
  {
    iso_3166_1: 'SU',
    english_name: 'Soviet Union',
    native_name: 'Soviet Union',
  },
  {
    iso_3166_1: 'SV',
    english_name: 'El Salvador',
    native_name: 'El Salvador',
  },
  {
    iso_3166_1: 'SY',
    english_name: 'Syrian Arab Republic',
    native_name: 'Syria',
  },
  {
    iso_3166_1: 'SZ',
    english_name: 'Swaziland',
    native_name: 'Eswatini (Swaziland)',
  },
  {
    iso_3166_1: 'TC',
    english_name: 'Turks and Caicos Islands',
    native_name: 'Turks & Caicos Islands',
  },
  {
    iso_3166_1: 'TD',
    english_name: 'Chad',
    native_name: 'Chad',
  },
  {
    iso_3166_1: 'TF',
    english_name: 'French Southern Territories',
    native_name: 'French Southern Territories',
  },
  {
    iso_3166_1: 'TG',
    english_name: 'Togo',
    native_name: 'Togo',
  },
  {
    iso_3166_1: 'TH',
    english_name: 'Thailand',
    native_name: 'Thailand',
  },
  {
    iso_3166_1: 'TJ',
    english_name: 'Tajikistan',
    native_name: 'Tajikistan',
  },
  {
    iso_3166_1: 'TK',
    english_name: 'Tokelau',
    native_name: 'Tokelau',
  },
  {
    iso_3166_1: 'TL',
    english_name: 'Timor-Leste',
    native_name: 'Timor-Leste',
  },
  {
    iso_3166_1: 'TM',
    english_name: 'Turkmenistan',
    native_name: 'Turkmenistan',
  },
  {
    iso_3166_1: 'TN',
    english_name: 'Tunisia',
    native_name: 'Tunisia',
  },
  {
    iso_3166_1: 'TO',
    english_name: 'Tonga',
    native_name: 'Tonga',
  },
  {
    iso_3166_1: 'TP',
    english_name: 'East Timor',
    native_name: 'East Timor',
  },
  {
    iso_3166_1: 'TR',
    english_name: 'Turkey',
    native_name: 'Turkey',
  },
  {
    iso_3166_1: 'TT',
    english_name: 'Trinidad and Tobago',
    native_name: 'Trinidad & Tobago',
  },
  {
    iso_3166_1: 'TV',
    english_name: 'Tuvalu',
    native_name: 'Tuvalu',
  },
  {
    iso_3166_1: 'TW',
    english_name: 'Taiwan',
    native_name: 'Taiwan',
  },
  {
    iso_3166_1: 'TZ',
    english_name: 'Tanzania',
    native_name: 'Tanzania',
  },
  {
    iso_3166_1: 'UA',
    english_name: 'Ukraine',
    native_name: 'Ukraine',
  },
  {
    iso_3166_1: 'UG',
    english_name: 'Uganda',
    native_name: 'Uganda',
  },
  {
    iso_3166_1: 'UM',
    english_name: 'United States Minor Outlying Islands',
    native_name: 'U.S. Outlying Islands',
  },
  {
    iso_3166_1: 'US',
    english_name: 'United States of America',
    native_name: 'United States',
  },
  {
    iso_3166_1: 'UY',
    english_name: 'Uruguay',
    native_name: 'Uruguay',
  },
  {
    iso_3166_1: 'UZ',
    english_name: 'Uzbekistan',
    native_name: 'Uzbekistan',
  },
  {
    iso_3166_1: 'VA',
    english_name: 'Holy See',
    native_name: 'Vatican City',
  },
  {
    iso_3166_1: 'VC',
    english_name: 'St. Vincent and the Grenadines',
    native_name: 'St. Vincent & Grenadines',
  },
  {
    iso_3166_1: 'VE',
    english_name: 'Venezuela',
    native_name: 'Venezuela',
  },
  {
    iso_3166_1: 'VG',
    english_name: 'British Virgin Islands',
    native_name: 'British Virgin Islands',
  },
  {
    iso_3166_1: 'VI',
    english_name: 'US Virgin Islands',
    native_name: 'U.S. Virgin Islands',
  },
  {
    iso_3166_1: 'VN',
    english_name: 'Vietnam',
    native_name: 'Vietnam',
  },
  {
    iso_3166_1: 'VU',
    english_name: 'Vanuatu',
    native_name: 'Vanuatu',
  },
  {
    iso_3166_1: 'WF',
    english_name: 'Wallis and Futuna Islands',
    native_name: 'Wallis & Futuna',
  },
  {
    iso_3166_1: 'WS',
    english_name: 'Samoa',
    native_name: 'Samoa',
  },
  {
    iso_3166_1: 'XC',
    english_name: 'Czechoslovakia',
    native_name: 'Czechoslovakia',
  },
  {
    iso_3166_1: 'XG',
    english_name: 'East Germany',
    native_name: 'East Germany',
  },
  {
    iso_3166_1: 'XI',
    english_name: 'Northern Ireland',
    native_name: 'Northern Ireland',
  },
  {
    iso_3166_1: 'XK',
    english_name: 'Kosovo',
    native_name: 'Kosovo',
  },
  {
    iso_3166_1: 'YE',
    english_name: 'Yemen',
    native_name: 'Yemen',
  },
  {
    iso_3166_1: 'YT',
    english_name: 'Mayotte',
    native_name: 'Mayotte',
  },
  {
    iso_3166_1: 'YU',
    english_name: 'Yugoslavia',
    native_name: 'Yugoslavia',
  },
  {
    iso_3166_1: 'ZA',
    english_name: 'South Africa',
    native_name: 'South Africa',
  },
  {
    iso_3166_1: 'ZM',
    english_name: 'Zambia',
    native_name: 'Zambia',
  },
  {
    iso_3166_1: 'ZR',
    english_name: 'Zaire',
    native_name: 'Zaire',
  },
  {
    iso_3166_1: 'ZW',
    english_name: 'Zimbabwe',
    native_name: 'Zimbabwe',
  },
]

export const movie_providers = {
  '2': 'https://tv.apple.com',
  '3': 'https://play.google.com/store/movies',
  '7': 'https://www.vudu.com',
  '8': 'https://www.netflix.com',
  '9': 'https://www.primevideo.com',
  '10': 'https://www.amazon.com/video',
  '11': 'https://mubi.com',
  '15': 'https://www.hulu.com',
  '19': 'https://www.netmovies.com',
  '20': 'https://www.maxdomestore.com',
  '21': 'https://www.stan.com',
  '25': 'https://www.fandor.com',
  '28': 'https://www.netzkino.com',
  '29': 'https://www.skygo.com',
  '30': 'https://www.wow.com',
  '33': 'https://www.alleskino.com',
  '34': 'https://www.mgmplus.com',
  '35': 'https://rakuten.tv',
  '38': 'https://www.bbc.co.uk/iplayer',
  '39': 'https://www.nowtv.com',
  '41': 'https://www.itvx.com',
  '43': 'https://www.starz.com',
  '47': 'https://www.looke.com',
  '54': 'https://www.boxoffice.com',
  '55': 'https://www.showmax.com',
  '58': 'https://www.canalvod.com',
  '59': 'https://www.bboxvod.com',
  '61': 'https://www.orangevod.com',
  '62': 'https://www.atresplayer.com',
  '63': 'https://www.filmin.com',
  '64': 'https://www.filminplus.com',
  '66': 'https://www.nuestrocinemx.com',
  '68': 'https://www.microsoftstore.com',
  '71': 'https://www.path\u00e9thuis.com',
  '72': 'https://www.videoland.com',
  '73': 'https://www.tubitv.com',
  '76': 'https://www.viaplay.com',
  '79': 'https://www.nbc.com',
  '80': 'https://www.amc.com',
  '82': 'https://www.tenplay.com',
  '83': 'https://www.thecw.com',
  '84': 'https://www.u-next.com',
  '87': 'https://www.acorntv.com',
  '97': 'https://www.watcha.com',
  '99': 'https://www.shudder.com',
  '100': 'https://www.guidedoc.com',
  '103': 'https://www.channel4.com',
  '109': 'https://www.timvision.com',
  '110': 'https://www.infinityplus.com',
  '113': 'https://www.ivi.com',
  '115': 'https://www.okko.com',
  '116': 'https://www.amediateka.com',
  '117': 'https://www.kinopoisk.com',
  '119': 'https://www.primevideo.com',
  '122': 'https://www.hotstar.com',
  '123': 'https://www.fxnow.com',
  '124': 'https://www.bookmyshow.com',
  '130': 'https://www.skystore.com',
  '132': 'https://www.sbsondemand.com',
  '133': 'https://www.videobuster.com',
  '134': 'https://www.foxtelnow.com',
  '135': 'https://www.abciview.com',
  '138': 'https://www.filmo.com',
  '140': 'https://www.cineplex.com',
  '143': 'https://www.sundancenow.com',
  '146': 'https://www.icitoutv.com',
  '147': 'https://www.m6plus.com',
  '148': 'https://www.abc.com',
  '149': 'https://www.movistarplusplusficci\u00f3ntotal.com',
  '150': 'https://www.bluetv.com',
  '151': 'https://www.britbox.com',
  '155': 'https://www.history.com',
  '157': 'https://www.lifetime.com',
  '158': 'https://www.viu.com',
  '159': 'https://www.catchplay.com',
  '160': 'https://www.iflix.com',
  '167': 'https://www.clarovideo.com',
  '175': 'https://www.netflixkids.com',
  '178': 'https://www.magentatv.com',
  '182': 'https://www.hollywoodsuite.com',
  '184': 'https://www.universalpictures.com',
  '185': 'https://www.screambox.com',
  '187': 'https://www.paramountpictures.com',
  '188': 'https://www.youtube.com/premium',
  '189': 'https://www.curzonhomecinema.com',
  '190': 'https://curiositystream.com',
  '191': 'https://www.kanopy.com',
  '192': 'https://www.youtube.com',
  '196': 'https://www.acorntvamazonchannel.com',
  '197': 'https://www.britboxamazonchannel.com',
  '199': 'https://www.fandoramazonchannel.com',
  '201': 'https://www.mubiamazonchannel.com',
  '202': 'https://www.screamboxamazonchannel.com',
  '204': 'https://www.shudderamazonchannel.com',
  '205': 'https://www.sundancenowamazonchannel.com',
  '207': 'https://www.therokuchannel.com',
  '209': 'https://www.pbs.com',
  '210': 'https://www.sky.com',
  '211': 'https://www.freeform.com',
  '212': 'https://www.hoopla.com',
  '219': 'https://www.ardmediathek.com',
  '222': 'https://www.raiplay.com',
  '224': 'https://www.bfiplayer.com',
  '230': 'https://www.crave.ca',
  '232': 'https://www.zee5.com',
  '234': 'https://www.arte.com',
  '235': 'https://www.youtubefree.com',
  '236': 'https://www.francetv.com',
  '237': 'https://www.sonyliv.com',
  '239': 'https://www.universcine.com',
  '246': 'https://www.7plus.com',
  '251': 'https://www.allblk.com',
  '257': 'https://www.fubotv.com',
  '258': 'https://www.criterionchannel.com',
  '260': 'https://www.wwenetwork.com',
  '268': 'https://www.historyvault.com',
  '273': 'https://www.neontv.com',
  '278': 'https://www.pureflix.com',
  '283': 'https://www.crunchyroll.com',
  '284': 'https://www.lifetimemovieclub.com',
  '285': 'https://www.bbcplayeramazonchannel.com',
  '286': 'https://www.zdfherzkinoamazonchannel.com',
  '287': 'https://www.bfiplayeramazonchannel.com',
  '289': 'https://www.cinemaxamazonchannel.com',
  '290': 'https://www.hallmarkplusamazonchannel.com',
  '291': 'https://www.mzchoiceamazonchannel.com',
  '293': 'https://www.pbskidsamazonchannel.com',
  '294': 'https://www.pbsmasterpieceamazonchannel.com',
  '295': 'https://www.retrocrushamazonchannel.com',
  '297': 'https://www.ziggotv.com',
  '298': 'https://www.rtlplus.com',
  '300': 'https://www.plutotv.com',
  '304': 'https://www.joyn.com',
  '305': 'https://www.cravestarz.com',
  '307': 'https://www.globoplay.com',
  '308': 'https://www.o2tv.com',
  '309': 'https://www.sunnxt.com',
  '310': 'https://www.lacinetek.com',
  '311': 'https://www.betvgo.com',
  '312': 'https://www.vrtmax.com',
  '314': 'https://www.cbcgem.com',
  '315': 'https://www.hoichoi.com',
  '319': 'https://www.altbalaji.com',
  '321': 'https://www.skyx.com',
  '322': 'https://www.usanetwork.com',
  '323': 'https://www.yleareena.com',
  '324': 'https://www.cinemasalademande.com',
  '326': 'https://www.ctv.com',
  '331': 'https://www.flixfling.com',
  '332': 'https://www.fandangoathomefree.com',
  '333': 'https://www.my5.com',
  '334': 'https://www.filmtasticamazonchannel.com',
  '337': 'https://www.disneyplus.com',
  '338': 'https://www.ruutu.com',
  '339': 'https://www.movistartv.com',
  '342': 'https://www.puhutv.com',
  '343': 'https://www.betplusamazonchannel.com',
  '344': 'https://www.rakutenviki.com',
  '349': 'https://www.kinoondemand.com',
  '350': 'https://www.appletvplus.com',
  '356': 'https://www.wavve.com',
  '357': 'https://www.docplay.com',
  '359': 'https://www.mediasetinfinity.com',
  '360': 'https://www.npostart.com',
  '361': 'https://www.tcm.com',
  '363': 'https://www.tnt.com',
  '368': 'https://www.indieflix.com',
  '370': 'https://www.vodclub.com',
  '373': 'https://www.go3.com',
  '378': 'https://www.9now.com',
  '381': 'https://www.canalplus.com',
  '383': 'https://www.tv2.com',
  '384': 'https://www.hbomax.com',
  '385': 'https://www.binge.com',
  '386': 'https://www.peacockpremium.com',
  '387': 'https://www.peacockpremiumplus.com',
  '389': 'https://www.sooner.com',
  '392': 'https://www.wedotv.com',
  '393': 'https://www.flixol\u00e9.com',
  '395': 'https://www.tvnzplus.com',
  '396': 'https://www.film1.com',
  '397': 'https://www.bbcamerica.com',
  '415': 'https://www.animationdigitalnetwork.com',
  '417': 'https://www.heretv.com',
  '421': 'https://www.joynplus.com',
  '423': 'https://www.blockbuster.com',
  '426': 'https://www.sfanytime.com',
  '430': 'https://www.hidive.com',
  '431': 'https://www.tv2play.com',
  '432': 'https://www.flixpremiere.com',
  '433': 'https://www.ovid.com',
  '434': 'https://www.ozflix.com',
  '435': 'https://www.drakenfilms.com',
  '436': 'https://www.fetchtv.com',
  '437': 'https://www.hungamaplay.com',
  '438': 'https://www.chaiflicks.com',
  '439': 'https://www.shout!factorytv.com',
  '440': 'https://www.threenow.com',
  '441': 'https://www.nfb.com',
  '442': 'https://www.nrktv.com',
  '443': 'https://www.filmstriben.com',
  '444': 'https://www.dekkoo.com',
  '446': 'https://www.retrocrush.com',
  '447': 'https://www.belasartes\u00e0lacarte.com',
  '448': 'https://www.beamafilm.com',
  '449': 'https://www.globaltv.com',
  '451': 'https://www.picl.com',
  '452': 'https://www.rtpplay.com',
  '455': 'https://www.nightflightplus.com',
  '456': 'https://www.mitele.com',
  '457': 'https://www.vix.com',
  '461': 'https://www.rtbfauvio.com',
  '463': 'https://www.kirjastokino.com',
  '464': 'https://www.kocowa.com',
  '466': 'https://www.bioskoponline.com',
  '467': 'https://www.directvgo.com',
  '468': 'https://www.genflix.com',
  '469': 'https://www.clubillico.com',
  '472': 'https://www.nlziet.com',
  '473': 'https://www.revry.com',
  '474': 'https://www.shemaroome.com',
  '475': 'https://www.docsville.com',
  '476': 'https://www.epicon.com',
  '477': 'https://www.gospelplay.com',
  '479': 'https://www.homeofhorror.com',
  '480': 'https://www.filmtastic.com',
  '481': 'https://www.arthousecnma.com',
  '482': 'https://www.manoramamax.com',
  '483': 'https://www.maxstream.com',
  '484': 'https://www.clarotvplus.com',
  '486': 'https://www.spectrumondemand.com',
  '488': 'https://www.tvo.com',
  '489': 'https://www.vidio.com',
  '491': 'https://www.cine.com',
  '493': 'https://www.svt.com',
  '496': 'https://www.cineasterna.com',
  '497': 'https://www.tele2play.com',
  '499': 'https://www.oldflix.com',
  '502': 'https://www.tataplay.com',
  '503': 'https://www.hi-yah.com',
  '505': 'https://www.player.com',
  '506': 'https://www.tbs.com',
  '507': 'https://www.trutv.com',
  '508': 'https://www.disneynow.com',
  '510': 'https://www.discoveryplus.com',
  '511': 'https://www.iwanttfc.com',
  '513': 'https://www.shadowz.com',
  '514': 'https://www.asiancrush.com',
  '515': 'https://www.mxplayer.com',
  '516': 'https://www.noovo.com',
  '517': 'https://www.triartplay.com',
  '520': 'https://www.discoveryplus.com',
  '522': 'https://www.popcorntimes.com',
  '524': 'https://www.discoveryplus.com',
  '525': 'https://www.knowledgenetwork.com',
  '526': 'https://www.amcplus.com',
  '528': 'https://www.amcplusamazonchannel.com',
  '529': 'https://www.arrow.com',
  '531': 'https://www.paramountplus.com',
  '532': 'https://www.aha.com',
  '533': 'https://www.amazonarthauschannel.com',
  '534': 'https://www.argo.com',
  '537': 'https://www.zdf.com',
  '538': 'https://www.plex.com',
  '539': 'https://www.viddla.com',
  '540': 'https://www.elisaviihde.com',
  '541': 'https://www.rtve.com',
  '542': 'https://www.filmfriend.com',
  '544': 'https://www.libreflix.com',
  '546': 'https://www.wowpresentsplus.com',
  '548': 'https://www.iffrunleashed.com',
  '550': 'https://www.tenk.com',
  '551': 'https://www.magellantv.com',
  '552': 'https://www.qftplayer.com',
  '553': 'https://www.teliaplay.com',
  '554': 'https://www.broadwayhd.com',
  '557': 'https://www.moretv.com',
  '559': 'https://www.filmzie.com',
  '560': 'https://www.filmoteket.com',
  '561': 'https://www.lionsgateplay.com',
  '562': 'https://www.moviesaints.com',
  '563': 'https://www.kpn.com',
  '567': 'https://www.truestory.com',
  '569': 'https://www.docalliancefilms.com',
  '570': 'https://www.premier.com',
  '572': 'https://www.rtlplay.com',
  '575': 'https://www.ondemandkorea.com',
  '576': 'https://www.klikfilm.com',
  '577': 'https://www.tvigle.com',
  '578': 'https://www.strim.com',
  '579': 'https://www.filmmovementplus.com',
  '580': 'https://www.novaplay.com',
  '581': 'https://www.iqiyi.com',
  '582': 'https://www.paramountplusamazonchannel.com',
  '583': 'https://www.mgmplusamazonchannel.com',
  '584': 'https://www.discoveryplusamazonchannel.com',
  '585': 'https://www.metrograph.com',
  '587': 'https://www.ifcamazonchannel.com',
  '588': 'https://www.mgmamazonchannel.com',
  '589': 'https://www.teletoonplusamazonchannel.com',
  '591': 'https://www.nowtvcinema.com',
  '593': 'https://www.stvplayer.com',
  '595': 'https://www.erosnowamazonchannel.com',
  '596': 'https://www.arrowvideoamazonchannel.com',
  '597': 'https://www.fullmoonamazonchannel.com',
  '599': 'https://www.pok\u00e9monamazonchannel.com',
  '600': 'https://www.shout!factoryamazonchannel.com',
  '602': 'https://www.filmboxliveamazonchannel.com',
  '603': 'https://www.curiositystreamamazonchannel.com',
  '604': 'https://www.docubayamazonchannel.com',
  '605': 'https://www.superchannelamazonchannel.com',
  '606': 'https://www.stacktvamazonchannel.com',
  '607': 'https://www.outtvamazonchannel.com',
  '608': 'https://www.lovenatureamazonchannel.com',
  '609': 'https://www.smithsonianchannelamazonchannel.com',
  '610': 'https://www.bbcearthamazonchannel.com',
  '612': 'https://www.allwaysblkamazonchannel.com',
  '613': 'https://www.amazonprimevideofreewithads.com',
  '614': 'https://www.vimoviesandtv.com',
  '615': 'https://www.w4free.com',
  '620': 'https://www.drtv.com',
  '621': 'https://www.nordiskfilmplus.com',
  '622': 'https://www.upctv.com',
  '623': 'https://www.wetv.com',
  '624': 'https://www.kktv.com',
  '625': 'https://www.linetv.com',
  '626': 'https://www.otta.com',
  '627': 'https://www.voyo.com',
  '628': 'https://www.edisonline.com',
  '629': 'https://www.osnplus.com',
  '630': 'https://www.starzplay.com',
  '631': 'https://www.hrti.com',
  '633': 'https://www.paramountplusrokupremiumchannel.com',
  '634': 'https://www.starzrokupremiumchannel.com',
  '635': 'https://www.amcplusrokupremiumchannel.com',
  '636': 'https://www.mgmplusrokupremiumchannel.com',
  '637': 'https://www.pickboxnow.com',
  '638': 'https://www.publicdomainmovies.com',
  '639': 'https://www.cinemember.com',
  '641': 'https://www.nexoplus.com',
  '642': 'https://www.studiocanalpresentsappletvchannel.com',
  '677': 'https://www.eventive.com',
  '678': 'https://www.filmlegendenamazonchannel.com',
  '679': 'https://www.cinemaofheartsamazonchannel.com',
  '680': 'https://www.bloodymoviesamazonchannel.com',
  '681': 'https://www.filmtotalamazonchannel.com',
  '683': 'https://www.lookeamazonchannel.com',
  '684': 'https://www.flixol\u00e9amazonchannel.com',
  '685': 'https://www.cineplusocsamazonchannel.com',
  '686': 'https://www.homeofhorroramazonchannel.com',
  '687': 'https://www.arthousecnmaamazonchannel.com',
  '688': 'https://www.shortstvamazonchannel.com',
  '689': 'https://www.tvcortosamazonchannel.com',
  '690': 'https://www.pongaloamazonchannel.com',
  '691': 'https://www.playsuisse.com',
  '692': 'https://www.cultpix.com',
  '693': 'https://www.turkonvideoamazonchannel.com',
  '696': 'https://www.serially.com',
  '697': 'https://www.mejane.com',
  '701': 'https://www.filmboxplus.com',
  '702': 'https://www.ibakatv.com',
  '704': 'https://www.irokotv.com',
  '705': 'https://www.hollywoodsuiteamazonchannel.com',
  '706': 'https://www.moviedomeplusamazonchannel.com',
  '707': 'https://www.aniverseamazonchannel.com',
  '708': 'https://www.superfreshamazonchannel.com',
  '1706': 'https://www.comedycentralplusamazonchannel.com',
  '1707': 'https://www.blutvamazonchannel.com',
  '1709': 'https://www.grjngoamazonchannel.com',
  '1711': 'https://www.mtvplusamazonchannel.com',
  '1712': 'https://www.rtlpassionamazonchannel.com',
  '1713': 'https://www.silverlineamazonchannel.com',
  '1715': 'https://www.shahidvip.com',
  '1717': 'https://www.acontraplus.com',
  '1718': 'https://www.espn.com',
  '1722': 'https://www.avavobb.com',
  '1723': 'https://www.avahbz.com',
  '1724': 'https://www.avacsal.com',
  '1725': 'https://www.avabgb.com',
  '1726': 'https://www.infinityselectionamazonchannel.com',
  '1727': 'https://www.cgcollectionamazonchannel.com',
  '1728': 'https://www.iwonderfullamazonchannel.com',
  '1729': 'https://www.fullactionamazonchannel.com',
  '1730': 'https://www.cinecomicoamazonchannel.com',
  '1732': 'https://www.universcineamazonchannel.com',
  '1733': 'https://www.actionmaxamazonchannel.com',
  '1734': 'https://www.filmoamazonchannel.com',
  '1735': 'https://www.insomniaamazonchannel.com',
  '1736': 'https://www.shadowzamazonchannel.com',
  '1737': 'https://www.inamadelenamazonchannel.com',
  '1738': 'https://www.benshiamazonchannel.com',
  '1740': 'https://www.planethorroramazonchannel.com',
  '1741': 'https://www.diziamazonchannel.com',
  '1742': 'https://www.acontraplusamazonchannel.com',
  '1743': 'https://www.historiayactualidadamazonchannel.com',
  '1744': 'https://www.iconfilmamazonchannel.com',
  '1745': 'https://www.curzonamazonchannel.com',
  '1746': 'https://www.hallmarktvamazonchannel.com',
  '1747': 'https://www.studiocanalpresentsamazonchannel.com',
  '1750': 'https://www.tod.com',
  '1754': 'https://www.tf1plus.com',
  '1756': 'https://www.filmingo.com',
  '1757': 'https://www.sooneramazonchannel.com',
  '1759': 'https://www.betplus.com',
  '1764': 'https://www.yorckondemand.com',
  '1768': 'https://www.espnplus.com',
  '1770': 'https://www.paramountpluswithshowtime.com',
  '1771': 'https://www.takflix.com',
  '1773': 'https://www.skyshowtime.com',
  '1788': 'https://www.loveandpassionamazonchannel.com',
  '1793': 'https://www.klassiki.com',
  '1794': 'https://www.starzamazonchannel.com',
  '1796': 'https://www.netflixstandardwithads.com',
  '1805': 'https://www.studiocanalpresentsmoviecultamazonchannel.com',
  '1806': 'https://www.studiocanalpresentsallstarsamazonchannel.com',
  '1811': 'https://www.cohenmediaamazonchannel.com',
  '1825': 'https://www.maxamazonchannel.com',
  '1826': 'https://www.todtv.com',
  '1829': 'https://www.behindthetree.com',
  '1832': 'https://www.popflick.com',
  '1838': 'https://www.tivify.com',
  '1852': 'https://www.britboxappletvchannel.com',
  '1853': 'https://www.paramountplusappletvchannel.com',
  '1854': 'https://www.amcplusappletvchannel.com',
  '1855': 'https://www.starzappletvchannel.com',
  '1856': 'https://www.magentatv.com',
  '1857': 'https://www.telenet.com',
  '1860': 'https://www.univervideo.com',
  '1861': 'https://www.filmow.com',
  '1866': 'https://www.vixpremiumamazonchannel.com',
  '1875': 'https://www.runtime.com',
  '1883': 'https://www.tving.com',
  '1887': 'https://www.brutxamazonchannel.com',
  '1888': 'https://www.animationdigitalnetworkamazonchannel.com',
  '1889': 'https://www.universalplusamazonchannel.com',
  '1891': 'https://www.alleskinoamazonchannel.com',
  '1892': 'https://www.rtlcrimeamazonchannel.com',
  '1894': 'https://www.cineautoreamazonchannel.com',
  '1895': 'https://www.animegenerationamazonchannel.com',
  '1896': 'https://www.rarovideoamazonchannel.com',
  '1897': 'https://www.midnightfactoryamazonchannel.com',
  '1898': 'https://www.amazonmxplayer.com',
  '1899': 'https://www.max.com',
  '1902': 'https://www.ardplus.com',
  '1904': 'https://www.tvplus.com',
  '1912': 'https://www.apollo.com',
  '1920': 'https://www.reservaimovision.com',
  '1928': 'https://www.primaplus.com',
  '1929': 'https://www.filmtasticbeicanalplus.com',
  '1939': 'https://www.lepsitv.com',
  '1944': 'https://www.tv4play.com',
  '1948': 'https://www.reveel.com',
  '1954': 'https://www.servustvon.com',
  '1956': 'https://www.angelstudios.com',
  '1957': 'https://www.cineverse.com',
  '1958': 'https://www.adtv.com',
  '1960': 'https://www.midnightpulp.com',
  '1961': 'https://www.allente.com',
  '1963': 'https://www.xumoplay.com',
  '1964': 'https://www.nationalgeographic.com',
  '1967': 'https://www.molotovtv.com',
  '1968': 'https://www.crunchyrollamazonchannel.com',
  '1971': 'https://www.distrotv.com',
  '1972': 'https://www.myfilmfriend.com',
  '1973': 'https://www.filmicca.com',
  '1976': 'https://www.outsidewatch.com',
  '1986': 'https://www.npoplus.com',
  '1988': 'https://www.brollie.com',
  '1989': 'https://www.zdfselectamazonchannel.com',
  '1990': 'https://www.glewedtv.com',
  '1993': 'https://www.videoload.com',
  '1994': 'https://www.tele5.com',
  '2029': 'https://www.mtvkatsomo.com',
  '2033': 'https://www.a&ecrimecentralappletvchannel.com',
  '2034': 'https://www.acorntvappletv.com',
  '2036': 'https://www.allblkappletvchannel.com',
  '2037': 'https://www.ardplusappletvchannel.com',
  '2038': 'https://www.arthausplusappletvchannel.com',
  '2040': 'https://www.betplusappletvchannel.com',
  '2041': 'https://www.bfiplayerappletvchannel.com',
  '2042': 'https://www.carnegiehallplusappletvchannel.com',
  '2044': 'https://www.outtvappletvchannel.com',
  '2045': 'https://www.upfaith&familyappletvchannel.com',
  '2047': 'https://www.tastemadeappletvchannel.com',
  '2048': 'https://www.sundancenowappletvchannel.com',
  '2049': 'https://www.shudderappletvchannel.com',
  '2050': 'https://www.screenpixappletvchannel.com',
  '2052': 'https://www.lovenatureappletvchannel.com',
  '2053': 'https://www.lionsgateplayappletvchannel.com',
  '2054': 'https://www.lifetimeplayappletvchannel.com',
  '2055': 'https://www.lifetimemovieclubappletvchannel.com',
  '2056': 'https://www.ifcfilmsunlimitedappletvchannel.com',
  '2057': 'https://www.historyvaultappletvchannel.com',
  '2058': 'https://www.hallmarkplusappletvchannel.com',
  '2059': 'https://www.erosnowselectappletvchannel.com',
  '2060': 'https://www.curiositystreamappletvchannel.com',
  '2061': 'https://www.cinemaxappletvchannel.com',
  '2064': 'https://www.allblkamazonchannel.com',
  '2065': 'https://www.ardplusamazonchannel.com',
  '2066': 'https://www.upfaith&familyamazonchannel.com',
  '2068': 'https://www.tastemadeamazonchannel.com',
  '2071': 'https://www.carnegiehallplusamazonchannel.com',
  '2073': 'https://www.historyvaultamazonchannel.com',
  '2074': 'https://www.lionsgateplayamazonchannel.com',
  '2075': 'https://www.lifetimeplayamazonchannel.com',
  '2076': 'https://www.wedotv.com',
  '2077': 'https://www.plexchannel.com',
  '2078': 'https://www.tromanow.com',
  '2081': 'https://www.kika.com',
  '2083': 'https://www.sonypictures.com',
  '2089': 'https://www.lifetimemovieclubamazonchannel.com',
  '2100': 'https://www.amazonprimevideowithads.com',
  '2101': 'https://www.canalplusonline.com',
  '2102': 'https://www.premierycanalplus.com',
  '2106': 'https://www.adrenalinapuraamazonchannel.com',
  '2107': 'https://www.adrenalinapuraappletvchannel.com',
  '2108': 'https://www.fareastamazonchannel.com',
  '2115': 'https://www.cinu.com',
  '2129': 'https://www.byutv.com',
  '2134': 'https://www.axnblackamazonchannel.com',
  '2135': 'https://www.kinofilmcollection.com',
  '2137': 'https://www.arthausplus.com',
  '2141': 'https://www.mgmplusamazonchannel.com',
  '2142': 'https://www.mgmplusappletvchannel.com',
  '2149': 'https://www.cgtv.com',
  '2151': 'https://www.orfon.com',
  '2152': 'https://www.orfkids.com',
  '2156': 'https://www.telecineamazonchannel.com',
  '2157': 'https://www.reservaimovisionamazonchannel.com',
  '2158': 'https://www.stingrayamazonchannel.com',
  '2159': 'https://www.curtaonamazonchannel.com',
  '2161': 'https://www.sonyoneamazonchannel.com',
  '2162': 'https://www.atresplayeramazonchannel.com',
  '2163': 'https://www.vixgratisamazonchannel.com',
  '2164': 'https://www.gaiaamazonchannel.com',
  '2167': 'https://www.cindieamazonchannel.com',
  '2168': 'https://www.docplayamazonchannel.com',
  '2169': 'https://www.iwonderamazonchannel.com',
  '2170': 'https://www.rialtoamazonchannel.com',
  '2173': 'https://www.animedigitalnetworkamazonchannel.com',
  '2174': 'https://www.strandreleasingamazonchannel.com',
  '2176': 'https://www.hoichoiamazonchannel.com',
  '2177': 'https://www.manoramamaxamazonchannel.com',
  '2178': 'https://www.chaupalamazonchannel.com',
  '2179': 'https://www.bbckidsamazonchannel.com',
  '2180': 'https://www.sonypicturesamazonchannel.com',
  '2181': 'https://www.vrottamazonchannel.com',
  '2182': 'https://www.animetimesamazonchannel.com',
  '2184': 'https://www.museumtvamazonchannel.com',
  '2185': 'https://www.nammaflixamazonchannel.com',
  '2190': 'https://www.plaionpictures.com',
  '2201': 'https://www.toggo.com',
  '2206': 'https://www.kixi.com',
  '2207': 'https://www.verleihshop.com',
  '2209': 'https://www.freenetmeinvod.com',
  '2211': 'https://www.3sat.com',
  '2214': 'https://www.cdapremium.com',
  '2220': 'https://www.akibapass.com',
  '2227': 'https://www.nflgamepassamazonchannel.com',
  '2229': 'https://www.disasterxamazonchannel.com',
  '2231': 'https://www.galacticstreamamazonchannel.com',
  '2233': 'https://www.battlezoneamazonchannel.com',
  '2235': 'https://www.tabii.com',
  '2237': 'https://www.3cat.com',
  '2239': 'https://www.flixhouse.com',
  '2241': 'https://www.movistarplusplus.com',
  '2243': 'https://www.appletvplusamazonchannel.com',
  '2244': 'https://www.asiaticamazonchannel.com',
  '2245': 'https://www.automotorundsportamazonchannel.com',
  '2246': 'https://www.axnwhiteamazonchannel.com',
  '2249': 'https://www.fixandfoxiamazonchannel.com',
  '2250': 'https://www.flimmerkistetvamazonchannel.com',
  '2252': 'https://www.franaticamazonchannel.com',
  '2253': 'https://www.geotelevisionamazonchannel.com',
  '2254': 'https://www.geowildamazonchannel.com',
  '2255': 'https://www.goodmoviesamazonchannel.com',
  '2256': 'https://www.gutelaunetvamazonchannel.com',
  '2257': 'https://www.historamaamazonchannel.com',
  '2258': 'https://www.kabeleinsclassicsamazonchannel.com',
  '2259': 'https://www.kinderweltamazonchannel.com',
  '2260': 'https://www.kixiselectamazonchannel.com',
  '2261': 'https://www.moconomyamazonchannel.com',
  '2263': 'https://www.netzkinoselectamazonchannel.com',
  '2264': 'https://www.okidokiamazonchannel.com',
  '2265': 'https://www.prosiebenfunamazonchannel.com',
  '2266': 'https://www.qelloconcertsbystingrayamazonchannel.com',
  '2267': 'https://www.queercinemabamazonchannel.com',
  '2268': 'https://www.rtllivingamazonchannel.com',
  '2269': 'https://www.sat.1emotionsamazonchannel.com',
  '2271': 'https://www.spiegelgeschichteamazonchannel.com',
  '2272': 'https://www.sportdigitalamazonchannel.com',
  '2273': 'https://www.stingrayclassicaamazonchannel.com',
  '2274': 'https://www.stingraydjazzamazonchannel.com',
  '2275': 'https://www.stingraykaraokeamazonchannel.com',
  '2277': 'https://www.terraxamazonchannel.com',
  '2278': 'https://www.tv1000russiankinoamazonchannel.com',
  '2279': 'https://www.waidwerkamazonchannel.com',
  '2281': 'https://www.wildwestamzonchannel.com',
  '2283': 'https://www.monomax.com',
  '2284': 'https://www.maxunextchannel.com',
  '2285': 'https://www.justwatchtv.com',
  '2286': 'https://www.vivabyvideofutur.com',
  '2287': 'https://www.adrenalinamazonchannel.com',
  '2288': 'https://www.allstarsamazonchannel.com',
  '2289': 'https://www.fernsehenmitherzamazonchannel.com',
  '2291': 'https://www.moviecultamazonchannel.com',
  '2292': 'https://www.redlightcinemaamazonchannel.com',
  '2293': 'https://www.sevenentertainmentamazonchannel.com',
  '2294': 'https://www.stingrayallgoodvibesamazonchannel.com',
  '2295': 'https://www.thrillboxamazonchannel.com',
  '2296': 'https://www.viaplayamazonchannel.com',
  '2297': 'https://www.zdfkrimiamazonchannel.com',
  '2298': 'https://www.zdftiviamazonchannel.com',
  '2299': 'https://www.bergblickamazonchannel.com',
  '2300': 'https://www.itvxpremium.com',
  '2302': 'https://www.mercadoplay.com',
  '2303': 'https://www.paramountpluspremium.com',
  '2304': 'https://www.paramountplusbasicwithads.com',
  '2307': 'https://www.premieremax.com',
  '2308': 'https://www.darkroom.com',
  '2311': 'https://www.channel4plus.com',
  '2314': 'https://www.acaciatvamazonchannel.com',
  '2315': 'https://www.adultswimamazonchannel.com',
  '2316': 'https://www.alchemiyaamazonchannel.com',
  '2317': 'https://www.allwarriornetworkamazonchannel.com',
  '2318': 'https://www.amebatvamazonchannel.com',
  '2320': 'https://www.aspiretvamazonchannel.com',
  '2321': 'https://www.befitamazonchannel.com',
  '2323': 'https://www.bestofbritishtvamazonchannel.com',
  '2324': 'https://www.baebleamazonchannel.com',
  '2325': 'https://www.bestwesternseveramazonchannel.com',
  '2326': 'https://www.broadwayhdamazonchannel.com',
  '2327': 'https://www.brownsugaramazonchannel.com',
  '2329': 'https://www.cartoonnetworkamazonchannel.com',
  '2330': 'https://www.joltfilm.com',
  '2336': 'https://www.jiohotstar.com',
  '2356': 'https://www.filmelierplusamazonchannel.com',
  '2357': 'https://www.filmpalastamazonchannel.com',
  '2358': 'https://www.lionsgateplusamazonchannels.com',
  '2359': 'https://www.geotelevisionpluswildamazonchannel.com',
  '2363': 'https://www.polsatboxgo.com',
  '2364': 'https://www.cinefestamazonchannel.com',
  '2365': 'https://www.cnnmaxamazonchannel.com',
  '2366': 'https://www.thecodacollectionamazonchannel.com',
  '2367': 'https://www.midnightpulpamazonchannel.com',
  '2369': 'https://www.daringdocsamazonchannel.com',
  '2371': 'https://www.dekkooamazonchannel.com',
  '2376': 'https://www.doccomamazonchannel.com',
  '2377': 'https://www.docuramafilmsamazonchannel.com',
  '2378': 'https://www.doveamazonchannel.com',
  '2379': 'https://www.doxamazonchannel.com',
  '2381': 'https://www.discoveryplusidamazonchannel.com',
  '2383': 'https://www.philo.com',
  '2388': 'https://www.eaglenolimitsamazonchannel.com',
  '2389': 'https://www.eaglemagicamazonchannel.com',
  '2390': 'https://www.hidiveamazonchannel.com',
  '2392': 'https://www.echoboomamazonchannel.com',
  '2393': 'https://www.cocinaonamazonchannel.com',
  '2394': 'https://www.fearfactoryamazonchannel.com',
  '2395': 'https://www.filmmovementplusamazonchannel.com',
  '2396': 'https://www.fitfusionamazonchannel.com',
  '2398': 'https://www.foodmattersamazonchannel.com',
  '2400': 'https://www.francechannelamazonchannel.com',
  '2401': 'https://www.fuseplusamazonchannel.com',
  '2403': 'https://www.hi-yahamazonchannel.com',
  '2404': 'https://www.indieclubamazonchannel.com',
  '2405': 'https://www.indieflixshortsamazonchannel.com',
  '2406': 'https://www.heretvamazonchannel.com',
  '2407': 'https://www.indiepixunlimitedamazonchannel.com',
  '2408': 'https://www.dokiamazonchannel.com',
  '2409': 'https://www.fawesome.com',
  '2411': 'https://www.eternalfamily.com',
  '2412': 'https://www.magentatvplus.com',
  '2414': 'https://www.kartoonchannelamazonchannel.com',
  '2415': 'https://www.kidstreamamazonchannel.com',
  '2418': 'https://www.mangoliaselectsamazonchannel.com',
  '2419': 'https://www.monstersandnightmaresamazonchannel.com',
  '2420': 'https://www.marqueetvamazonchannel.com',
  '2424': 'https://www.outsidetvfeaturesamzonchannel.com',
  '2425': 'https://www.ownamazonchannel.com',
  '2427': 'https://www.passionflixamazonchannel.com',
  '2428': 'https://www.pinoyboxofficeamazonchannel.com',
  '2429': 'https://www.pbsamericaamazonchannel.com',
  '2430': 'https://www.pbsdocumentariesamazonchannel.com',
  '2431': 'https://www.pbslivingamazonchannel.com',
  '2432': 'https://www.pixlamazonchannel.com',
  '2433': 'https://www.greatamericanpureflixamazonchannel.com',
  '2435': 'https://www.revryamazonchannel.com',
  '2436': 'https://www.ryanandfriendsplusamazonchannel.com',
  '2439': 'https://www.zenlifebystingrayamazonchannel.com',
  '2441': 'https://www.tcmamazonchannel.com',
  '2442': 'https://www.demandafricaamazonchannel.com',
  '2443': 'https://www.thesurfnetworkamazonchannel.com',
  '2444': 'https://www.tokuamazonchannel.com',
  '2445': 'https://www.moviesphereplusamazonchannel.com',
  '2446': 'https://www.trueroyaltyamazonchannel.com',
  '2448': 'https://www.fueltvplusamazonchannel.com',
  '2450': 'https://www.bongflixamazonchannel.com',
  '2452': 'https://www.dreamscapekidsamazonchannel.com',
  '2454': 'https://www.greenplanetstreamamazonchannel.com',
  '2462': 'https://www.yogaandfitnesstvamazonchannel.com',
  '2465': 'https://www.vemoxcineamazonchannel.com',
  '2466': 'https://www.warriorsandgangstersamazonchannel.com',
  '2467': 'https://www.xivetvdocumentariesamazonchannel.com',
  '2468': 'https://www.xltvamazonchannel.com',
  '2469': 'https://www.docsvilleamazonchannel.com',
  '2470': 'https://www.yipeekidstvamazonchannel.com',
  '2472': 'https://www.maxoriginalsamazonchannel.com',
  '2474': 'https://www.paramountplusoriginalsamazonchannel.com',
  '2475': 'https://www.paramountplusmtvamazonchannel.com',
  '2478': 'https://www.foundtv.com',
  '2479': 'https://www.stupidco.com',
  '2480': 'https://www.gaiamtvyoga&fit.com',
  '2481': 'https://www.cinemixplusamazonchannel.com',
  '2483': 'https://www.mymoviesone.com',
  '2484': 'https://www.abcondemandamazonchannel.com',
  '2486': 'https://www.asiapremiumamazonchannel.com',
  '2487': 'https://www.bloomeplusamazonchannel.com',
  '2488': 'https://www.boxbrazilplayamazonchannel.com',
  '2489': 'https://www.kadokawachannelamazonchannel.com',
  '2491': 'https://www.channelkamazonchannel.com',
  '2492': 'https://www.channelkyofuamazonchannel.com',
  '2493': 'https://www.cinefilwowplusamazonchannel.com',
  '2494': 'https://www.danimeamazonchannel.com',
  '2498': 'https://www.fodchannelamazonchannel.com',
  '2499': 'https://www.indiefilmsbyrealtoamazonchannel.com',
  '2500': 'https://www.jidiaigekisenmonchannelamazonchannel.com',
  '2502': 'https://www.kinofilmsplusamazonchannel.com',
  '2503': 'https://www.koreandramachannelamazonchannel.com',
  '2505': 'https://www.leminoselectamazonchannel.com',
  '2507': 'https://www.necoplusamazonchannel.com',
  '2508': 'https://www.myheroamazonchannel.com',
  '2509': 'https://www.nhkkodomoparkamazonchannel.com',
  '2511': 'https://www.nihoneiganetamazonchannel.com',
  '2513': 'https://www.plusgagaamazonchannel.com',
  '2514': 'https://www.plusshochikuamazonchannel.com',
  '2515': 'https://www.havingfunwithshimajiroamazonchannel.com',
  '2517': 'https://www.bs10starchannelexamazonchannel.com',
  '2518': 'https://www.telesaamazonchannel.com',
  '2519': 'https://www.toeianimationchannelamazonchannel.com',
  '2520': 'https://www.toeiondemandamazonchannel.com',
  '2523': 'https://www.crankeduptv.com',
  '2525': 'https://www.superchannelplus.com',
  '2526': 'https://www.madeineuropeamazonchannel.com',
  '2527': 'https://www.arovisionaotearoa.com',
}

export const one_pixel_placeholder =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMUW+y1HwADngHEN2ffBQAAAABJRU5ErkJggg=='
